name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
